services:
  - type: web
    name: hero-nestjs-api
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PYTHON_API_URL
        value: https://hero-python-api.onrender.com 